<?php

namespace app\admin\controller;

// 文章类
class Article extends Common
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->setTabs();
    }

    private function setTabs(array $tabs = [])
    {
        $this->assign('tabs', array_merge([
            '文章列表'  => url('/admin/article_list'),
            '添加文章'  => url('/admin/article_add'),
        ], $tabs));
    }

    private function setCategorys()
    {
        $this->assign('categorys', model('Category')->where('delete_time', null)->select());
    }

    // 文章列表
    public function table()
    {
        $this->setTitle('文章列表');

        $articles = model('Article')->with('User')->with('Category')->where('delete_time', null)->order(['id' => 'desc'])->paginate(10);
        if (empty($articles))
        {
            $this->assign('msg', '没有文章');
        }
        else
        {
            $this->assign('articles', $articles);
        }
        return view();
    }

    // 添加文章
    public function add()
    {
        if (request()->isPost())
        {
            $result = model('Article')->add(input('post.'));
            if (1 == $result)
            {
                $this->success('添加成功', '/admin/article_list');
            }
            $this->assign('msg', $result);
        }
        $this->setTitle('添加文章');
        $this->setCategorys();
        return view();
    }

    // 编辑保存文章
    public function edit($id=0)
    {
        if (request()->isPost())
        {
            $result = model('Article')->edit($id, input('post.'));
            if (1 == $result)
            {
                $this->success('保存成功', '/admin/article_list');
            }
            $this->assign('msg', $result);
        }
        $article = model('Article')->with('ArticleContent')->find($id);
        if ($article)
        {
            $this->assign('article', $article);
        }
        else
        {
            $this->assign('msg', '不存在文章');
        }
        $this->setCategorys();
        $this->setTitle('编辑文章');
        $this->setTabs(['编辑文章' => 'javascript:void(0)']);
        return view();
    }

    // 删除文章
    public function del($id)
    {
        if (model('Article')->destroy($id)) $this->success('删除成功', '/admin/article_list');
        $this->error('删除失败', 'admin/article_list');
    }
}
